apiVersion: v1
kind: Pod
metadata:
  name: nfs-pod
  labels:
    name: nginx-pod
spec:
  volumes:
    - name: www
      persistentVolumeClaim:
          claimName: volume-claim
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
        - name: www
          mountPath: /usr/share/nginx/html
      resources:
          limits:
            cpu: 500m
            memory: 500Mi
