apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
  labels:
    name: main
spec:
  storageClassName: manual
  capacity: 
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.31.103
    path: "/mnt/nfs_share"
