apiVersion: v1
kind: Pod
metadata:
  name: busybox3
spec:
  volumes:
  - name: host-volume
    persistentVolumeClaim:
      claimName: pvc3
  containers:
  - image: busybox
    name: busybox3
    command: ["/bin/sh"]
    args: ["-c", "sleep 600"]
    volumeMounts:
    - name: host-volume
      mountPath: /temp/lol