apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-dynamic-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dynamic-nfs-pod
  template:
    metadata:
      labels:
        app: dynamic-nfs-pod
      name: dynamic-nfs-pod
    spec:
      volumes:
        - name: nfs-volume
          nfs:
            server: 192.168.31.103
            path: /mnt/nfs_share
      containers:
        - name: dynamic-nfs-pod
          image: quay.io/external_storage/nfs-client-provisioner:latest

          env:
            - name: PROVISIONER_NAME
              value: example.com/nfs
            - name: NFS_SERVER
              value: 192.168.31.103
            - name: NFS_PATH
              value: /mnt/nfs_share

          volumeMounts:
            - name: nfs-volume
              mountPath: /temp/lolz
