apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: bash
spec:
  schedule: '*/1 * * * *'
  jobTemplate:
    metadata:
      name: bash
    spec:
      template:
        metadata:
          name: bash
        spec:
          volumes:
            - name: cron-vol
              persistentVolumeClaim:
                  claimName: main-volume-claim
          restartPolicy: Never
          containers:
          - image: bash
            name: bash
            args:
            - bash
            - -c
            - hostname >> /tmp/vol/storage
            volumeMounts:
              - mountPath: /tmp/vol/
                name: cron-vol
            
